### ISSUE TITLE
/scrape command grabs the grid midjourney image

### ISSUE THREAD

**Issue by jfhutchi** [seemywingz/ponder#37]
/scrape should not grab the image that is 4 images.

**Comment by vekjja** [comment]
This is the intended behavior.
https://github.com/seemywingz/ponder/blob/main/cmd/Discord_api.go#L174
the bot mentions this as a response
```
"Scraping Discord Channel for ALL Image URLs and sending them to #saved-images.\nAll `Upscaled` Midjourney Images will be sent to Printify as well..."
```

But we can make it smarter and have it only save upscaled images. 
And potentially make it smart enough to only save the last X images or images in a date range.

**Comment by vekjja** [comment]
I removed the scrpae command and the printify API to cleanup and streamline the functionality
